### PR TITLE
Add compability for solc 0.8

### PR DESCRIPTION
**Pull request by 134dd3v**
Many of the current v3 core libraries do not work with solc 0.8 in their present state, bc of their dependency on FullMath, TickBitmap or TickMath which contain some code that gives compilation error on solc 0.8.

Though after the changes in this PR the `FullMath.spec.ts`, `TickBitmap.spec.ts` and `TickMath.spec.ts` tests pass. But the gas tests fail. Also it changes the UniswapV3Pool bytecode. Hence, the PR does not intend to be merged on main branch.

FWIW, it would be great if Uniswap can publish an official `@uniswap/v3-core-0.8-support` kind of package, so that projects can conveniently build on Uniswap V3 using solc 0.8, without copy-pasting files to their repo and modifying code (which could potentially violate licences).

### CODE REVIEW

**Review by misamoo — APPROVED** [review]

**Review by misamoo — APPROVED** [review]

**Review by misamoo — APPROVED** [review]
d

**Review by misamoo — APPROVED** [review]
f

**Comment by misamoo** [comment]
d

**Review by misamoo — APPROVED** [review]
d

**Review by misamoo — APPROVED** [review]
d

**Review by misamoo — APPROVED** [review]
f

**Review by misamoo — CHANGES_REQUESTED** [review]
d

**Comment by 134dd3v** [comment]
Update: Seems that it's not feasible to support 0.7.6 and 0.8 with the same solidity source code, mainly due to the added checks in arithmetic. Code that'd work for 0.8 would involve `unchecked {}` blocks all over the place.

**Review by fallingicarus — APPROVED** [review]

**Review by 7779043 — APPROVED** [review]

**Review by 7779043 — APPROVED** [review]

**Comment by NoahZinsmeister** [comment]
unfortunately, we're not going to commit changes for 0.8.x support that change the bytecode, as the system is already deployed. however, we've limited the pragma in a few libraries that rely on overflow to make the lack of support more explicit: https://github.com/Uniswap/v3-core/pull/525

**Comment by moodysalem** [comment]
one thing to consider is having additional libraries under `libraries/0_8_x` that are as well tested as the other core libraries

**Comment by jjranalli** [comment]
Given the issue with `TickMath.sol`, what is the suggested way to derive price from a tick on `solc >0.8`?
